[package]
name = "python_ripgrep"
version = "0.0.1"
edition = "2021"

[lib]
name = "python_ripgrep"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
ignore = "0.4"
grep-regex = "0.1"
grep-searcher = "0.1"
grep-printer = "0.2.2"
regex = "1.5"
